---
title: "Introduction to Python"
date: "`r format(Sys.time(), '%B, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Description about Course/Book."
favicon: assets/dasl_favicon.ico
output:
    bookdown::word_document2:
      toc: true
---

# About this Course {.unnumbered}

## Curriculum

The course covers fundamentals of Python, a high-level programming language, and use it to wrangle data for analysis and visualization.

## Target Audience

The course is intended for researchers who want to learn coding for the first time with a data science application via the Python language. This course is also appropriate for folks who have explored data science or programming on their own and want to focus on some fundamentals.

## Learning Objectives

**Analyze** Tidy datasets in the Python programming language via data subsetting, joining, and transformations.

**Evaluate** summary statistics and data visualization to understand scientific questions.

**Describe** how the Python programming environment interpret complex expressions made out of functions, operations, and data structures, in a step-by-step way.

**Apply** problem solving strategies to debug broken code.

## Offerings

This course is taught on a regular basis at [Fred Hutch Cancer Center](https://www.fredhutch.org/) through the [Data Science Lab](https://hutchdatascience.org/). Announcements of course offering can be found [here](https://hutchdatascience.org/training/).
