---
title: "W6: Getting Python on your computer"
format: 
  revealjs:
    smaller: true
    scrollable: true
    echo: true
---

## We did it!

[You are now comfortable with our code from Week 1!](https://colab.research.google.com/drive/1_77QQcj0mgZOWLlhtkZ-QKWUP1dnSt-_?usp=sharing)

[Your Cheatsheet](https://docs.google.com/document/d/171UZo7cg_6dIaJF1nucKiawgQKXoTl1LzRPpCFmI4fc/edit?tab=t.0#heading=h.o6ug7zunarm)

## Certification/Badging

Certification upon completing 4 out of the 5 assignments: <https://www.credly.com/org/fred-hutch/badge/intro-to-python>

What it is:

-   A display of what you accomplished in the course, shareable in your professional networks such as LinkedIn, similar to online education services such as Coursera.

What it isn't:

-   Accreditation through an university or degree-granting program.

I've been keeping track of folks' completion [here](https://docs.google.com/spreadsheets/d/1mv3OKnf4l2lYNxPPLy3PLnktZCCvUrio9F9HeCTBJfE/edit?gid=0#gid=0).

## Continuing your education

-   [Intermediate Python](https://hutchdatascience.org/Intermediate_Python/) (live class TBD)
-   [Machine Learning for Python](https://ocdo.fredhutch.org/dasl/courses/machine-learning-python/) (Spring 2026)
-   Reference texts:
    -   [Python for Data Analysis](https://wesmckinney.com/book/)

## Connecting to rest of Data Science Lab...

-   [Data House Calls](https://ocdo.fredhutch.org/programs/dhc.html)

-   [Building Computational Workflows Workshop, March 11 at noon](https://forms.office.com/r/YPxrxaw421)

## Please fill out survey!

[Our class survey](https://forms.gle/EwtYWTNBARz4koLbA) makes a huge difference for us.

## Install Python on your computer

### Windows

Open up Command Prompt, type: `python3`

Might take you to Microsoft Store to install Python 3.x

### Mac

Open up Terminal (under Applications/Utilities folder), type: `python3`

If nothing comes up, download at: <https://www.python.org/downloads/>

## Python Integrated Development Environment (IDE)

-   [Positron](https://positron.posit.co/) is built for data science applications

-   [VSCode](https://code.visualstudio.com/) is highly popular with experienced programmers

-   [PyCharm](https://www.jetbrains.com/pycharm/) is also very popular

### Install

-   <https://positron.posit.co/download.html>

## Getting Started - Notebook style

Create a new folder from template. Everything for the project, such as code and data will be in this folder.

-   Use Jupyter Notebooks

-   Select a folder name and directory of your choice

-   Select virual environment

-   Should open up a blank notebook for you.

There may be a step request to install Jupyter Notebooks extensions. Accept the request.

## Install Python Packages/Modules

In the Console type: `%pip install [package name]`

## Practice reading in data locally

-   Save your notebook.

-   Create a folder `data/` in your project directory.

-   Place `ex1.csv`, `ex2.csv`, `ex3.csv` in the `data/` folder.

. . .

-   The **absolute directory path** specifies the directory from the root directory: `/Users/clo2/Documents/python_project/data/ex1.csv`
-   The **relative directory path** is a path *relative to our current directory*: `data/ex1.csv`

. . .

-   The symbol `..` specifies the parent directory. If we are currently at `/Users/clo2/Documents/python_project/notebooks`, then we have to access our file via `../ex1.csv`.

## Practice reading in data locally

Here's an example data:

```         
a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo
```

We read it in as:

```{python}
import pandas as pd
my_df = pd.read_csv("data/ex1.csv")
my_df
```

## Dealing with headers

A dataset sometimes might not have column names/headers....

```         
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo
```

```{python}
import pandas as pd
my_df = pd.read_csv("data/ex2.csv", header=None)
my_df
```

. . .

We can assign columns:

```{python}
my_df = pd.read_csv("data/ex2.csv", names=["a", "b", "c", "d", "message"])
my_df
```

## Other weird things - skipping certain rows

```         
# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo
```

```{python}
my_df = pd.read_csv("data/ex3.csv", skiprows=[0, 2, 3])
my_df
```

## Other file formats

`pd.read_excel("example.xlsx")` for excel files

`pd.read_excel("example.xlsx", sheet_name = "chickwts")` for excel files with a sheet name

`pd.read_table()` for general-deliminated files, such as:

`pd.read_table("file.tsv", sep = "\t")`

## Writing out data

`my_df.to_csv( "filepath.csv")`

`my_df.to_excel("filepath.xlsx")`

`my_df.to_table("filepath.tsv", sep="\t")`

## Saving plots

```         
myplot = sns.displot(data=metadata, x="Age", col="Sex", multiple="dodge", binwidth= 10)
myplot.savefig("myplot.png")
```

## Project and spreadsheet organization

Consider having subfolders for:

-   Raw data and metadata

-   Analyzed data

-   Plots

[Good enough practices for scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)

[Better Spreadsheet workshop](https://better-spreadsheets.netlify.app/)

## Appendix: Python Environments

An **"Environment"** in Python is the context in which a Python program runs that consists of a Python interpreter and any number of installed packages.

-   The "**Global Environment"** is the default Python installation, with its interpreter and installed packages.

-   The "**Local Environment**" is a secondary Python installation, built specifically for a project. It is good practice to always have a local environment in a project you are working on, so that the Python interpreter and package are version controlled. (Also known as Virtual Environments)

    -   There are several software that manages these local environments for you:
        -   [uv](https://docs.astral.sh/uv/)
        -   [Virtual Environment](https://docs.python.org/3/library/venv.html)
        -   [Conda](https://docs.conda.io/en/latest/)
